### ISSUE TITLE
Clicking "Next" on the TFT Bulk Tool advances the page even if there is no more pages

### ISSUE THREAD

**Issue by ericellb** [PoeStack/poestack-next#39]
Repro steps
- Pull up any stash tab in the TFT bulk tool
- Click next, when there is no next page
- Every time you click next, will move to the next page even if there is no data
- Forces you to click back as many times as you clicked next

A simple check on whether there is a next page, and disable the button / not advance the index would be an easy fix.

LOW PRIORITY

**Comment by ericellb** [comment]
Seems like in `src/components/item-table/snapshot-item-table.tsx` you are setting `hasMore={true}` by default.

**Comment by zach-herridge** [comment]
Should be fixed now.
