### ISSUE TITLE
[Bulk selling tool] Mark bulk post as sold

### ISSUE THREAD

**Issue by LukAssArts** [PoeStack/poestack-next#42]
Since you can't edit any posts of the TFT-One-Click bot I think it would be nice if you had a button besides "Post to TFT" that could mark the latest bulk post as sold.

Maybe it's possible to grab the bots latest message that mentioned the discord userhandle in the according bulk selling channel and edit it to strike-through/sold?

**Comment by zach-herridge** [comment]
Moved https://github.com/PoeStack/issues/issues/42 here
