### ISSUE TITLE
Do not post anything if nothing was selected

### ISSUE THREAD

**Issue by SkyHomage** [PoeStack/poestack-next#48]
Steps to produce:

1. Select a tab
2. Select a tab type
3. Accidentally click "Post to TFT" instead of "Grab Items"

This will lead you posting to TFT with nothing selected for 0c and waiting for the cooldown. You shouldnt be able to post to TFT with nothing selected or a total value of 0c.

**Comment by zach-herridge** [comment]
This will now cause an error without posting.
