### ISSUE TITLE
SSPL is not an OSI open source license

### ISSUE THREAD

**Issue by jjstewart** [PoeStack/poestack-next#57]
This project uses the words "fully open source" on its home page though it is licensed under SSPL, which is NOT an open-source license. There is a reason MongoDB withdrew it from OSI consideration. All OSI-approved licenses are found at https://opensource.org/licenses/

By calling a project "open source" without having an open-source license, you may create the impression that the project follows the principles and practices of open source, including transparency and community collaboration. However, without a proper open-source license, users may not have the same rights and freedoms they expect from open-source software.

**Comment by zach-herridge** [comment]
The license accomplishes code transparency which what people asked for when they requested I release the source. I'm not interested in being listed on OSI. The license, privacy policy, and TOS are all very available I'm not sure how much more clear I could be in conveying rights and freedoms to users.
