### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by krolikmvp** [PoeStack/poestack-next#88]
Application error: a client-side exception has occurred (see the browser console for more information).

This message appears on the middle of the screen whe I try to go to the [https://poestack.com/tft/bulk-tool link](https://poestack.com/tft/bulk-tool?league=Ancestor)

![image](https://github.com/PoeStack/poestack-next/assets/12802749/d920b1cb-41ee-487d-857b-ac53f9c2c5e2)

**Comment by krolikmvp** [comment]
[poestack.com-1694435014322.log](https://github.com/PoeStack/poestack-next/files/12575928/poestack.com-1694435014322.log)

**Comment by Jzir** [comment]
@krolikmvp fixed via https://github.com/PoeStack/poestack-next/pull/91
